# Generated by Django 4.1.2 on 2023-04-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating_count_tot', models.IntegerField()),
                ('user_rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size_bytes', models.BigIntegerField()),
                ('rating_count_ver', models.IntegerField()),
                ('user_rating_ver', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ver', models.CharField(max_length=20)),
                ('cont_rating', models.CharField(max_length=10)),
                ('prime_genre', models.CharField(max_length=50)),
                ('sup_devices_num', models.IntegerField()),
                ('ipadSc_urls_num', models.IntegerField()),
                ('lang_num', models.IntegerField()),
                ('vpp_lic', models.BooleanField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_data.product')),
            ],
            options={
                'db_table': 'product_detail',
            },
        ),
    ]
