# Generated by Django 4.1.2 on 2023-04-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='user_rating_ver',
            field=models.CharField(max_length=10),
        ),
    ]
