# Generated by Django 4.1.2 on 2023-04-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_data', '0002_alter_product_price_alter_product_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_count_tot',
            field=models.CharField(max_length=10),
        ),
    ]
