# Generated by Django 4.1.2 on 2023-04-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_data', '0003_alter_product_rating_count_tot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='rating_count_ver',
            field=models.CharField(max_length=10),
        ),
    ]
